site_name: HCableAnalysis
site_description: Suspension Bridge Cable Analysis Framework
site_author: Structural Simulation Lab
repo_url: https://github.com/structuralsimulationlab/HCableAnalysis

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - Documentation: Documentation.md
  - Theory: theory.md
  - EngineeringCases: EngineeringCases.md
  - Benchmark: benchmark.md
  - Roadmap: roadmap.md
