site_name: HCableAnalysis
site_description: A Suspension Bridge Cable Analysis Framework
site_author: HCableAnalysis Team
repo_url: https://github.com/HCableAnalysis/HCableAnalysis

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Theory: theory.md
  - Examples: examples.md
  - Benchmark: benchmark.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

copyright: Copyright &copy; 2026 HCableAnalysis
