site_name: HCableAnalysis
site_description: Suspension Bridge Cable Analysis Framework
site_author: Structural Simulation Lab
repo_url: https://github.com/structuralsimulationlab/HCableAnalysis

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - Documentation: Documentation.md
  - Theory: theory.md
  - Engineering Cases:
      - Overview: EngineeringCases/EngineeringCases.md
      - Case 001 - Chacao Bridge: EngineeringCases/EngineeringCases001/EngineeringCases001.md
      - Case 003 - Huangjiaoping Bridge: EngineeringCases/EngineeringCases003/EngineeringCases003.md
  - Benchmark: benchmark.md
  - Roadmap: roadmap.md
